import type { IQuestion } from 'src/types/question';

import { fSub } from 'src/utils/format-time';

import { _mock } from './_mock';

export const _questions: IQuestion[] = [
  {
    id: _mock.id(1),
    name: 'Full Name',
    isRequired: true,
    inputType: 'text',
    order: 1,
    createdAt: fSub({ days: 1 }),
    updatedAt: fSub({ days: 1 }),
  },
  {
    id: _mock.id(2),
    name: 'Email Address',
    isRequired: true,
    inputType: 'email',
    order: 2,
    createdAt: fSub({ days: 2 }),
    updatedAt: fSub({ days: 2 }),
  },
  {
    id: _mock.id(3),
    name: 'Phone Number',
    isRequired: false,
    inputType: 'tel',
    order: 3,
    createdAt: fSub({ days: 3 }),
    updatedAt: fSub({ days: 3 }),
  },
  {
    id: _mock.id(4),
    name: 'Country',
    isRequired: true,
    inputType: 'select',
    order: 4,
    options: ['United States', 'Canada', 'United Kingdom', 'Australia'],
    createdAt: fSub({ days: 4 }),
    updatedAt: fSub({ days: 4 }),
  },
  {
    id: _mock.id(5),
    name: 'Gender',
    isRequired: false,
    inputType: 'radio',
    order: 5,
    options: ['Male', 'Female', 'Other'],
    createdAt: fSub({ days: 5 }),
    updatedAt: fSub({ days: 5 }),
  },
  {
    id: _mock.id(6),
    name: 'Interests',
    isRequired: false,
    inputType: 'checkbox',
    order: 6,
    options: ['Technology', 'Sports', 'Music', 'Travel'],
    createdAt: fSub({ days: 6 }),
    updatedAt: fSub({ days: 6 }),
  },
  {
    id: _mock.id(7),
    name: 'Age',
    isRequired: true,
    inputType: 'number',
    order: 7,
    createdAt: fSub({ days: 7 }),
    updatedAt: fSub({ days: 7 }),
  },
  {
    id: _mock.id(8),
    name: 'Birth Date',
    isRequired: false,
    inputType: 'date',
    order: 8,
    createdAt: fSub({ days: 8 }),
    updatedAt: fSub({ days: 8 }),
  },
  {
    id: _mock.id(9),
    name: 'Website',
    isRequired: false,
    inputType: 'url',
    order: 9,
    createdAt: fSub({ days: 9 }),
    updatedAt: fSub({ days: 9 }),
  },
  {
    id: _mock.id(10),
    name: 'Resume',
    isRequired: true,
    inputType: 'file',
    order: 10,
    createdAt: fSub({ days: 10 }),
    updatedAt: fSub({ days: 10 }),
  },
];
