import type { FontOption, ColorPalette } from 'src/types/theme-configuration';

export const colorPalettes: ColorPalette[] = [
  {
    id: 'material-blue',
    name: 'Material Blue',
    colors: {
      primary: '#1976d2',
      secondary: '#dc004e',
      background: '#ffffff',
      surface: '#f5f5f5',
      text: '#212121',
      success: '#2e7d32',
      warning: '#ed6c02',
      error: '#d32f2f',
      info: '#0288d1',
    },
  },
  {
    id: 'material-purple',
    name: 'Material Purple',
    colors: {
      primary: '#7b1fa2',
      secondary: '#f50057',
      background: '#ffffff',
      surface: '#f5f5f5',
      text: '#212121',
      success: '#2e7d32',
      warning: '#ed6c02',
      error: '#d32f2f',
      info: '#0288d1',
    },
  },
  {
    id: 'material-green',
    name: 'Material Green',
    colors: {
      primary: '#388e3c',
      secondary: '#f50057',
      background: '#ffffff',
      surface: '#f5f5f5',
      text: '#212121',
      success: '#2e7d32',
      warning: '#ed6c02',
      error: '#d32f2f',
      info: '#0288d1',
    },
  },
  {
    id: 'dark-theme',
    name: 'Dark Theme',
    colors: {
      primary: '#90caf9',
      secondary: '#f48fb1',
      background: '#121212',
      surface: '#1e1e1e',
      text: '#ffffff',
      success: '#4caf50',
      warning: '#ff9800',
      error: '#f44336',
      info: '#2196f3',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    colors: {
      primary: '#000000',
      secondary: '#666666',
      background: '#ffffff',
      surface: '#fafafa',
      text: '#000000',
      success: '#00c853',
      warning: '#ff6f00',
      error: '#d50000',
      info: '#0091ea',
    },
  },
  {
    id: 'corporate',
    name: 'Corporate',
    colors: {
      primary: '#1565c0',
      secondary: '#424242',
      background: '#f8f9fa',
      surface: '#ffffff',
      text: '#212529',
      success: '#28a745',
      warning: '#ffc107',
      error: '#dc3545',
      info: '#17a2b8',
    },
  },
];

export const fontOptions: FontOption[] = [
  {
    id: 'roboto',
    name: 'Roboto',
    family: 'Roboto, sans-serif',
    category: 'sans-serif',
    preview: 'Aa',
  },
  {
    id: 'inter',
    name: 'Inter',
    family: 'Inter, sans-serif',
    category: 'sans-serif',
    preview: 'Aa',
  },
  {
    id: 'open-sans',
    name: 'Open Sans',
    family: 'Open Sans, sans-serif',
    category: 'sans-serif',
    preview: 'Aa',
  },
  {
    id: 'lato',
    name: 'Lato',
    family: 'Lato, sans-serif',
    category: 'sans-serif',
    preview: 'Aa',
  },
  {
    id: 'poppins',
    name: 'Poppins',
    family: 'Poppins, sans-serif',
    category: 'sans-serif',
    preview: 'Aa',
  },
  {
    id: 'playfair',
    name: 'Playfair Display',
    family: 'Playfair Display, serif',
    category: 'serif',
    preview: 'Aa',
  },
  {
    id: 'merriweather',
    name: 'Merriweather',
    family: 'Merriweather, serif',
    category: 'serif',
    preview: 'Aa',
  },
  {
    id: 'fira-code',
    name: 'Fira Code',
    family: 'Fira Code, monospace',
    category: 'monospace',
    preview: 'Aa',
  },
  {
    id: 'source-code-pro',
    name: 'Source Code Pro',
    family: 'Source Code Pro, monospace',
    category: 'monospace',
    preview: 'Aa',
  },
];
