import type { ThemePreset } from 'src/types/theme-configuration';

export const defaultThemePresets: ThemePreset[] = [
  {
    id: 'material-light',
    name: 'Material Light',
    description: 'Clean and modern Material Design light theme',
    category: 'built-in',
    preview: '',
    configuration: {
      primaryColor: '#1976d2',
      secondaryColor: '#dc004e',
      backgroundColor: '#ffffff',
      surfaceColor: '#f5f5f5',
      textColor: '#212121',
      accentColors: {
        success: '#2e7d32',
        warning: '#ed6c02',
        error: '#d32f2f',
        info: '#0288d1',
      },
      navLayout: 'vertical',
      sidebarWidth: 'normal',
      headerStyle: 'fixed',
      contentSpacing: 24,
      gridColumns: 12,
      gridGap: 16,
      fontFamily: {
        primary: 'Roboto, sans-serif',
        secondary: 'Roboto, sans-serif',
      },
      fontSize: {
        base: 16,
        scale: 1.2,
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        bold: 700,
      },
      lineHeight: 1.5,
      letterSpacing: 0,
      borderRadius: 8,
      shadowIntensity: 'medium',
      animations: true,
      blurIntensity: 0,
      transparency: 1,
    },
  },
  {
    id: 'material-dark',
    name: 'Material Dark',
    description: 'Modern Material Design dark theme',
    category: 'built-in',
    preview: '',
    configuration: {
      primaryColor: '#90caf9',
      secondaryColor: '#f48fb1',
      backgroundColor: '#121212',
      surfaceColor: '#1e1e1e',
      textColor: '#ffffff',
      accentColors: {
        success: '#4caf50',
        warning: '#ff9800',
        error: '#f44336',
        info: '#2196f3',
      },
      navLayout: 'vertical',
      sidebarWidth: 'normal',
      headerStyle: 'fixed',
      contentSpacing: 24,
      gridColumns: 12,
      gridGap: 16,
      fontFamily: {
        primary: 'Roboto, sans-serif',
        secondary: 'Roboto, sans-serif',
      },
      fontSize: {
        base: 16,
        scale: 1.2,
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        bold: 700,
      },
      lineHeight: 1.5,
      letterSpacing: 0,
      borderRadius: 8,
      shadowIntensity: 'heavy',
      animations: true,
      blurIntensity: 0,
      transparency: 1,
    },
  },
  {
    id: 'minimal-light',
    name: 'Minimal Light',
    description: 'Clean and minimal light theme',
    category: 'built-in',
    preview: '',
    configuration: {
      primaryColor: '#000000',
      secondaryColor: '#666666',
      backgroundColor: '#ffffff',
      surfaceColor: '#fafafa',
      textColor: '#000000',
      accentColors: {
        success: '#00c853',
        warning: '#ff6f00',
        error: '#d50000',
        info: '#0091ea',
      },
      navLayout: 'vertical',
      sidebarWidth: 'compact',
      headerStyle: 'static',
      contentSpacing: 32,
      gridColumns: 12,
      gridGap: 24,
      fontFamily: {
        primary: 'Inter, sans-serif',
        secondary: 'Inter, sans-serif',
      },
      fontSize: {
        base: 14,
        scale: 1.25,
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        bold: 600,
      },
      lineHeight: 1.6,
      letterSpacing: -0.01,
      borderRadius: 4,
      shadowIntensity: 'light',
      animations: false,
      blurIntensity: 0,
      transparency: 1,
    },
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    description: 'Professional corporate theme with blue accents',
    category: 'built-in',
    preview: '',
    configuration: {
      primaryColor: '#1565c0',
      secondaryColor: '#424242',
      backgroundColor: '#f8f9fa',
      surfaceColor: '#ffffff',
      textColor: '#212529',
      accentColors: {
        success: '#28a745',
        warning: '#ffc107',
        error: '#dc3545',
        info: '#17a2b8',
      },
      navLayout: 'horizontal',
      sidebarWidth: 'normal',
      headerStyle: 'fixed',
      contentSpacing: 20,
      gridColumns: 12,
      gridGap: 20,
      fontFamily: {
        primary: 'Open Sans, sans-serif',
        secondary: 'Open Sans, sans-serif',
      },
      fontSize: {
        base: 15,
        scale: 1.15,
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        bold: 600,
      },
      lineHeight: 1.4,
      letterSpacing: 0,
      borderRadius: 6,
      shadowIntensity: 'medium',
      animations: true,
      blurIntensity: 0,
      transparency: 1,
    },
  },
];
